default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= Rails.application.credentials.db_password %>

development:
  <<: *default
  database: api_dev
  username: <%= Rails.application.credentials.db_username %>
  host: <%= Rails.application.credentials.db_host %>
 
test:
  <<: *default
  database: api_test
  username: <%= Rails.application.credentials.db_username %>
  host: <%= Rails.application.credentials.db_host %>

production:
  <<: *default
  database: api_prod
  username: <%= Rails.application.credentials.db_username %>
  host: <%= Rails.application.credentials.db_host %>